version: "3.9"
services:
    db:
        image: "mcr.microsoft.com/mssql/server:2019-latest"
        environment:
            SA_PASSWORD: "EqW!tty2022"
            ACCEPT_EULA: "Y"
        ports:
            - "1433:1433"
        volumes:
            - ./DbData:/var/opt/mssql/data
        container_name: "Ekviti-DB"
            
    api:
        image: "ekviti/api:${Environment}-latest"
        ports:
            - "4001:80"
        container_name: "Ekviti-API"
        depends_on:
            - db

    mailhog:
        image: mailhog/mailhog
        logging:
           driver: 'none'
        container_name: "Ekviti-MailHog"
        ports:
           - 1025:1025
           - 8025:8025